SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"
ROOT_ENV_FILE="$ROOT_DIR/.env.local"
SUPABASE_SCRIPT="$ROOT_DIR/infra/db/scripts/supabase.sh"
